defaultContentLanguage: 'en'
defaultContentLanguageInSubdir: true

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    noHl: false
    style: native
    tabWidth: 4

timeZone: "UTC"

markup:
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
  goldmark:
    duplicateResourceFiles: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    noHl: false
    style: native
    tabWidth: 4
  diagrams:
    enable: true
    theme: default

disableKinds:
- "404"
- home
- robotsTXT
- RSS
#- section
- sitemap
- taxonomy
- term

enableGitInfo: true

sitemap:
  filename: "sitemap.xml"
  priority: 0.75

params:
  # The same as in the /products/<APP>/ doc URL prefix
  productCode: development-platform
  analytics:
    google: XXXX
    yandex: XXXX
  # GitHub repository link for editing a page and opening issues.
  github_repo: https://github.com/deckhouse/development-platform
  # Show "Edit this page" link
  showedit: true

  # Enable Lunr.js offline search
  offlineSearch: false

  # Global relevant links.
  links:

# See the tdewolff/minify project page for details
minify:
  tdewolff:
    html:
      keepComments: false
      keepDefaultAttrVals: true
      keepDocumentTags: true
      keepEndTags: true
      keepQuotes: true
      keepSpecialComments: true
      keepWhitespace: false
    json:
      keepNumbers: true
      precision: 0
    svg:
      keepComments: false
      precision: 0
    xml:
      keepWhitespace: false

module:
  imports:
    - path: github.com/deckhouse/hugo-web-product-module

languages:
  en:
    disabled: false
    languageDirection: ""
    languageName: ""
    title: Deckhouse Development Platform
    weight: 0
    baseURL: https://deckhouse.io/products/development-platform/
    params:
      description: ""
  ru:
    disabled: false
    languageDirection: ""
    languageName: ""
    weight: 1
    title: Deckhouse Development Platform
    baseURL: https://deckhouse.ru/products/development-platform/
    params:
      description: ""
